### ISSUE TITLE
Instructions to use massif for personal media collections

### ISSUE THREAD

**Issue by parfait8566** [rsimmons/massif#10]
Say I have cloned massif and have a bunch of .epubs or subtitles files and want to use them for indexed sentences, how I'd do it?
I guess this is the most important part of the code for this: https://github.com/rsimmons/massif/tree/master/backend/intake
But there are no instructions so I'm not really sure

**Comment by rsimmons** [comment]
Thanks for your interest in Massif.

Unfortunately it would be very difficult to run sentence scoring on your own, which is the key feature of Massif. Also, part of the reason that Massif works (sorta) well is that it draws on a very large set of sentences, around 30 million.

I made the code public in case people were curious how something worked, but I never intended for people to get it running on their own.

I'm curious, why do you want to sort your own sentences by quality/score? What is the overall learning approach you have in mind?

**Comment by parfait8566** [comment]
> Thanks for your interest in Massif.
> 
> Unfortunately it would be very difficult to run sentence scoring on your own, which is the key feature of Massif. Also, part of the reason that Massif works (sorta) well is that it draws on a very large set of sentences, around 30 million.
> 
> I made the code public in case people were curious how something worked, but I never intended for people to get it running on their own.
> 
> I'm curious, why do you want to sort your own sentences by quality/score? What is the overall learning approach you have in mind?

Massif seems to be biased towards fantasy novels. Being able to use your own personal library would be cool and you'd be able to use it with other media (like visual novels) or more recent books.

**Comment by rsimmons** [comment]
In my experience, sorting sentences by quality/score is not useful unless you have a very large corpus. I'm not sure a typical personal library would be big enough. Also, the way I've been scoring sentences (using AI) would be prohibitively expensive for most people.

But I agree it would be good to expand the Massif corpus to include sources beyond fantasy novels. I may get around to that at some point in the future.
