### ISSUE TITLE
Add a search API?

### ISSUE THREAD

**Issue by Morgawr** [rsimmons/massif#3]
Hey, just wanna say I love this project and use it pretty much every day, so I'm incredibly thankful for it :)

I think it'd be nice if there was an API to return results of sentences rather than just a web page (if there is and I'm completely oblivious to it then please lmk). 

Something like searching for \<word\> could return a JSON file of example sentences containing \<word\>, etc etc.

**Comment by rsimmons** [comment]
Thanks for the positive feedback!

Yes, this will not be too hard to add, I will look into it soon-ish.

**Comment by rsimmons** [comment]
Sorry this ended up taking a while to get to, but it should now be supported. For example:
https://massif.la/ja/search?q=%E3%81%8A%E5%BE%85%E3%81%9F%E3%81%9B%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F&fmt=json
