### ISSUE TITLE
massif.la website seems down/unreachable?

### ISSUE THREAD

**Issue by Morgawr** [rsimmons/massif#9]
I tried going to https://massif.la/ja and it seems like the website is timing out. Not sure if it's a DNS issue but I am getting ERR_NAME_NOT_RESOLVED 

Just in case you weren't aware.

**Comment by tchin25** [comment]
Same here

**Comment by rsimmons** [comment]
I'm not able to reproduce this, it's working fine for me. I had a couple people in other countries check and it works for them currently as well. Are you still seeing this problem? Maybe it was transient.

**Comment by tchin25** [comment]
It's back for me as well

**Comment by Morgawr** [comment]
Yup, I can confirm it's back for me as well. Maybe it was a temporary DNS issue. I guess we can close this?

**Comment by rsimmons** [comment]
Cool, thanks for reporting tho.
